# Create Complete R Package "mestools"
# This script creates a fully-featured R package with all components
# Author: Lucas VHH TRAN <tranhungydhcm@gmail.com>
# GitHub: https://github.com/vanhungtran/mestools

# Load required packages
required_packages <- c("usethis", "devtools", "desc", "pkgdown", "knitr", "rmarkdown", "here")
invisible(lapply(required_packages, function(pkg) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    install.packages(pkg)
  }
  library(pkg, character.only = TRUE)
}))

# Configuration - CORRECTED PATH DEFINITION
package_name <- basename(here::here())
pkg_name <- "mestools"
pkg_path <- file.path(dirname(here::here()), pkg_name)
GITHUB_REPO <- paste0("https://github.com/vanhungtran/", pkg_name, ".git")
author_name <- "Lucas VHH TRAN"
author_email <- "tranhungydhcm@gmail.com"
github_username <- "vanhungtran"

func_names <- c("mestools-package", "mestools-core", "mestools-utils")

message("===========================================")
message("Creating package '", pkg_name, "'...")
message("Package path: ", pkg_path)
message("GitHub repo: ", GITHUB_REPO)
message("Author: ", author_name)
message("Email: ", author_email)
message("===========================================")


# Ensure package directory exists
if (!dir.exists(pkg_path)) {
  # Create basic package at the specified path
  create_package(path = pkg_path, rstudio = TRUE, open = FALSE)
  1
  message("✓ Initialized package structure")
  message("✓ Created package directory: ", pkg_path)
} else {
  message("✓ Package directory already exists: ", pkg_path)
}


# Set working directory to package
setwd(pkg_path)

# 1. BASIC PACKAGE SETUP
message("📦 1. Setting up basic package structure...")



# Package description with all fields
use_description(
  list(
    Package = pkg_name,
    Title = "A Collection of Useful Tools for Data Analysis and Package Development",
    Description = "Provides utility functions for data manipulation, package development, deployment automation, and common analytical tasks. Includes GitHub deployment automation and quality of life tools for R developers.",
    `Authors@R` = c(
      person(given = "Lucas VHH", family = "TRAN",
             email = "tranhungydhcm@gmail.com",
             role = c("aut", "cre"))
    ),
    Version = "0.1.0",
    License = "MIT + file LICENSE",
    URL = paste0("https://github.com/", github_username, "/", pkg_name),
    BugReports = paste0("https://github.com/", github_username, "/", pkg_name, "/issues"),
    Depends = "R (>= 4.0.0)",
    Imports = "utils, stats, tools, devtools, usethis, gert, here, desc, pkgdown, knitr, rmarkdown, testthat",
    Suggests = "rmarkdown, knitr, spelling, pkgload, curl, gh, covr",
    VignetteBuilder = "knitr",
    Encoding = "UTF-8"
  )
)

# 2. LICENSE
message("📄 2. Adding MIT license...")
use_mit_license("Lucas VHH TRAN")

# 3. DIRECTORY STRUCTURE
message("📁 3. Creating directory structure...")

# Create standard directories
dir.create("R", showWarnings = FALSE, recursive = TRUE)
dir.create("man", showWarnings = FALSE, recursive = TRUE)
dir.create("vignettes", showWarnings = FALSE, recursive = TRUE)
dir.create("inst", showWarnings = FALSE, recursive = TRUE)
dir.create("tests/testthat", showWarnings = FALSE, recursive = TRUE)
dir.create("inst/doc", showWarnings = FALSE, recursive = TRUE)
dir.create("data", showWarnings = FALSE, recursive = TRUE)






# 4. CORE R FUNCTIONS




message("⚙️  4. Creating core R functions...")

# Create each R file
for (func in func_names) {
  r_file <- file.path("R", paste0(func, ".R"))

  if (!file.exists(r_file)) {
    usethis::use_r(func, open = FALSE)
    message("✓ Created: ", func, ".R")
  } else {
    message("○ Already exists: ", func, ".R")
  }
}

message("\nCompleted! Created ", length(func_names), " R files in mestools package.")





# Step 6: Create NAMESPACE if it doesn't exist
if (!file.exists("NAMESPACE")) {
  writeLines(
    c(
      "# Generated by roxygen2: do not edit by hand",
      "",
      "exportPattern(\"^[[:alpha:]]+\")"
    ),
    con = "NAMESPACE"
  )
  message("✓ Created NAMESPACE file")
}

# Final message
message(paste0("\n", strrep("=", 50)))
message("🎉 Package '", pkg_name, "' created successfully!")
message("📁 Package location: ", normalizePath(getwd()))
message("🌐 GitHub repository: ", GITHUB_REPO)
message(strrep("=", 50))
message("\n📦 Next steps:")
message("  1. Review and customize the package metadata")
message("  2. Add your specific functions to R/ directory")
message("  3. Run tests: devtools::test()")
message("  4. Build documentation: devtools::document()")
message("  5. Check package: devtools::check()")
message("  6. Deploy: Rscript deploy.R")
message("\n🚀 Your mestools package is ready for development!")
message("\n💡 Quick commands to get started:")
message("   setwd('", getwd(), "')")
message("   devtools::load_all()")
message("   devtools::test()")
message("   Rscript deploy.R 'Initial commit'")

# Return to original directory
setwd("..")

message("\n✅ Package creation complete! Happy coding! 🎊")







